
## Comparing objects

### Overview

section for comparing objects

### comparing scalars

```{r "comparing scalars"}
1 == 1L           # not strict
identical(1, 1L)  # strict

x1 <- 0.5 - 0.3
x2 <- 0.3 - 0.1
x1 == x2          # FALSE on most machines
all.equal(x1, x2) # TRUE everywhere
```

### comparing vectors

```{r "comparing vectors"}
v1 <- 1:3               # integer
v2 <- c(2-1, 3-1, 4-1)  # double
v1 == v2
all.equal(v1, v2)
identical(v1, v2)

v1s <- c(2,3,1) # order significant, naturally
v1 == v1s
all.equal(v1, v1s)

```

comparing named vectors

```{r "comparing named vectors"}

v3n <- c(`a` = 1, b = 2)
v3ns <- c(b = 2, `a` = 1)
v3n == v3ns
all.equal(v3n, v3ns)

```

### comparing lists

```{r "comparing lists"}

l1 <- list(aa = 1, bb = 2)
l2 <- list(bb = 2, aa = 1)
all.equal(l1, l2, check.attributes = FALSE) # l1 == l2 # not implemented

```

order insignificant list comparison

```{r }

isEquivalentList <- function(list1, list2){
  if(length(list1) != length(list2)) return(FALSE)
  setdiff(list1, list2) %>% isEmpty
}
l3 <- list(bb = 2, aa = 1, cc = 3)
l4 <- list(bb = 2, aa = 31)
l5 <- list(2, 1)
isEquivalentList(l1, l2)
isEquivalentList(l2, l1)
isEquivalentList(l3, l1)
isEquivalentList(l1, l3)

isEquivalentList(l1, l4) # checks values

isEquivalentList(l1, l5) # does not check names

isEquivalentList(v1, v2) # works on vectors too

```

